spring:
  application:
    name: task
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/task
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: postgresql